#!/bin/bash
set -e

# Create databases
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE ${POSTGRES_DB};
    CREATE DATABASE ${POSTGRES_DB_TEST};
    CREATE DATABASE ${POSTGRES_DB_PROD};
EOSQL
