name: Node.js CI

env:
  POSTGRES_HOST: POSTGRES_HOST
  POSTGRES_USER: POSTGRES_USER
  POSTGRES_PASSWORD: POSTGRES_PASSWORD
  POSTGRES_DB: POSTGRES_DB
  POSTGRES_DB_TEST: POSTGRES_DB_TEST
  POSTGRES_DB_PROD: POSTGRES_DB_PROD
  PGADMIN_DEFAULT_EMAIL: PGADMIN_DEFAULT_EMAIL
  PGADMIN_DEFAULT_PASSWORD: PGADMIN_DEFAULT_PASSWORD
  DB_PORT: DB_PORT
  TOKEN_SECRET: TOKEN_SECRET
  SALT_ROUNDS: SALT_ROUNDS
  PEPPER: PEPPER

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.5.0

      - name: Show current directory
        run: |
          echo "Current directory is: $(pwd)"
          echo "Listing the contents:"
          ls -la

      - name: Install Backend dependencies
        run: |
          npm install -g pnpm
          pnpm install

      - name: Run Backend tests
        run: |
          pnpm test
